name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  token:
    description: 'github token'
    required: true
    default: ''
  issues:
    description: 'Issues to move'
    required: true
    default: ''
  from_column:
    description: 'Column to move issues from'
    required: true
    default: ''
  to_column:
    description: 'Column to move issues to'
    required: true
    default: ''
outputs:
  moved_issues:
    description: 'Comma-delimited list of issues that were moved'
runs:
  using: 'node12'
  main: 'index.js'